[build]
  command = "npm run build"
  publish = ".next"
  base = "frontend"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://ruthan-api.c5f5f834f23e4dd583899f1e02518a40.workers.dev" # Replace with actual Koyeb URL
  NEXT_PUBLIC_SUPABASE_URL = "https://ccwnnradnszbwjfjfpvk.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "REDACTED_SUPABASE_KEY"
